version: "3.9"
networks:
  deploy-guide-dev:
    driver: bridge
services:
  taskmanager.server:
    image: ${DOCKER_REGISTRY-}taskmanagerserver
    container_name: deploy-guide
    build:
      context: .
      dockerfile: TaskManager/Server/Dockerfile
    ports:
      - "80:80"
    networks:
      - deploy-guide-dev
    depends_on:
      - postgres_db
  postgres_db:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 101001Zeus
      POSTGRES_DB: task_manager
    ports:
      - "5432:5432"
    networks:
      - deploy-guide-dev
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data: