version: '3.4'

networks:
  dev:
    driver: bridge

services:
  taskmanager.server:
    image: docker.io/library/taskmanagerserver
    depends_on:
        - "app_db"
    container_name: taskmanager-services
    ports:
        - "8088:80"
    build:
      context: .
      dockerfile: TaskManager/Server/Dockerfile
    environment:
        - ConnectionStrings__DbConnection=User ID=postgres;Password=101001Zeus;Server=app_db;Port=5432;Database=task_manager;IntegratedSecurity=true;Pooling=true;
        - ASPNETCORE_URLS=http://+:80
    networks:
        - dev

  app_db:
      image: postgres:latest
      container_name: app_db
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 101001Zeus
        POSTGRES_DB: task_manager
      ports:
          - "5433:5432"
      restart: always
      volumes:
        - app_data:/var/lib/postgresql/data
      networks:
        - dev

volumes:
    app_data: